### PR TITLE
JD - Cleanup Analyze Reactions Page

### PR DESCRIPTION
**Pull request by ucsbjasonrdunne**
The following features were implemented to the Analyze Reactions Page: "Users show up as their profile names rather than their user id" and "Links are clickable."  The original issue can be found at: https://github.com/ucsb-cs156-s21/proj-mapache-search/issues/170

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
Please make the title concise and a complete phrase or sentence.

Then, make the description a standalone description of what the PR does, from the user standpoint.

It would help to have screenshots.

**Review by pconrad — CHANGES_REQUESTED** [review]
Fix the eslint issues highlighted, and also fix this failing test:

```
AnalyzeReactions tests › Fetch is called once and with correct url when user clicks on search button
```

**Review by emilyomahony — CHANGES_REQUESTED** [review]
Generally, the LAs have asked us to use `let` instead of `var` for scoping reasons. You can pretty much just replace it everywhere, although you might have to add another `let` on line 33 of `MessageTableReaction.js`. Also they want us to replace the class zoom link with some other link

**Review by sarahkwon — APPROVED** [review]
LGTM. Tested locally

**Pull request closed without merging**
