### PR TITLE
7pm-3 md, bl, and jc - tagged user display

### LINKED ISSUE #74: Make tagged users stand out and make them links
In https://github.com/ucsb-cs156-f20/proj-mapache-search/pull/63  the code was modified so that the ids such as the ones seen here like `U017218J9B3`, `<@U019G97PMPE>` `<@U01BZGQNC20>`, etc. get replaced with human readable names:

image

Here's what the output looks like after the change:

image

But there is an improvement that can be made: In Slack, these appear with shading to make it clear that these were "tagged users", not just someone typing in the user's name.  Compare ` `@Yiwei Zhang` and `@Lyuda Panina (she/her)` with `Andrew` in the output below.

image

What we'd like to do in this story is make the tagged users in the output appear differently.  We can use a `<span></span>` tag with a custom CSS class, for example, or maybe something already built into react-bootstrap.   It would be helpful if this were a custom component so that we can customize it later in one place in the front end code.

### LINKED ISSUE #273: User IDs are not replaced when viewing as a member not an admin
# Bug Report

When viewing search results as a member and not an admin, user names appear as IDs. This is also affecting ability to test in #272 

# Steps to Reproduce

Running locally on WSL 2 in a Chrome window

1. Be a member and not an admin
2. Go to the Slack Search page and search for a simple word like "test"
3. Look for a message that includes a user tag, which will be displayed as an ID

# Expected / Desired Behavior

User names should replace the IDs just as they do when viewed as an admin

# Observed / Actual Behavior

User IDs remain unchanged when viewed as a member

# Screenshots and Logs

image
image

### PR DESCRIPTION
**Pull request by mdeirossi**
In this PR, we add a blue highlight to tagged users in both MessageListView and MessageScrollableView so tags are more easily visible and resemble those on Slack.
Closes #74 

Additionally, there was an issue where the slackUsers api required admin permission to use, so the user IDs were not being converted to names when logged in as a member. See [issue 273](https://github.com/ucsb-cs156-s21/proj-mapache-search/issues/273) for details, this PR also closes #273

### CODE REVIEW

**Review by TranNicholas — APPROVED** [review]
LGTM

**Review by alvin-tu — APPROVED** [review]
LGTM

**Review by TranNicholas — COMMENTED** [review]
I guess it would be nice to get these changes into `SearchResultsView` as well, but I think that that can be part of a larger refactor issue since the 3 views basically share the same code right now except that it is manually duplicated.

**Review by TranNicholas — APPROVED** [review]
LGTM

**Review by mara-downing — APPROVED** [review]
LGTM

**Pull request merged**
