### PR TITLE
NW/VS - 7pm-4 - Replaced old favicon logo with a new one

### PR DESCRIPTION
**Pull request by Vanessa-Salgado**
User sees a different favicon icon on each web page.

### CODE REVIEW

**Review by karankhangura — DISMISSED** [review]
LGTM

**Review by JacquelineMai — CHANGES_REQUESTED** [review]
When deployed on Heroku, the favicon doesn't show up. It likely works locally because you have the file locally- be sure to add the PNG file to `javascript/public` and push it on this branch so that it's added to the repo!

**Comment by nicomwong** [comment]
Okay, I pushed the new favicon image to the repo. It seems to have fixed the problem when deploying on Heroku.

**Review by JacquelineMai — APPROVED** [review]
LGTM

**Review by karankhangura — APPROVED** [review]
LGTM

**Pull request merged**
