### PR TITLE
7pm-2 Align submit button with search input box on search tab of Google search page.

### PR DESCRIPTION
**Pull request by ujcookcao**
Before:
image

After:
image
Align submit button with search input box on search tab of Google search page.
so that users could find the search button easier.
This is achieved by editing the javascript\src\main\pages\Search\Search.js file
On line 90, I edited the offset of the submit button.

### CODE REVIEW

**Comment by michaelwyl** [comment]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
Please add a more detailed description.
> adjust submit button position

What submit button?  There may be dozens of them in the app.  Specify exactly which page, either by describing how you navigate to the page, or by the URL of the page.

Adjust how?  And why?  

A before and after screenshot is the best way to show this.

**Comment by pconrad** [comment]
This is not a code review:

image


To count as a code review, you need to go through the Files Changed tab, and then the Review Changes button.

**Comment by ujcookcao** [comment]
image
Align submit button with search input box on search tab of Google search page.
so that users could find the search button easier.
This is achieved by editing the javascript\src\main\pages\Search\Search.js file
On line 90, I edited the offset of the submit button.

**Review by michaelwyl — DISMISSED** [review]
The submit button is now in the place as indicated. LGTM

**Comment by andrewhlu** [comment]
> image
> Align submit button with search input box on search tab of Google search page.
> so that users could find the search button easier.
> This is achieved by editing the javascript\src\main\pages\Search\Search.js file
> On line 90, I edited the offset of the submit button.

It looks like you just added a new comment instead of editing the description. You can edit the description by clicking the three dots above the current description.

**Comment by ujcookcao** [comment]
> > image
> > Align submit button with search input box on search tab of Google search page.
> > so that users could find the search button easier.
> > This is achieved by editing the javascript\src\main\pages\Search\Search.js file
> > On line 90, I edited the offset of the submit button.
> 
> It looks like you just added a new comment instead of editing the description. You can edit the description by clicking the three dots above the current description.

I did not find where it says "description", do you mean the title?

**Comment by andrewhlu** [comment]
This is what I'm referring to when I say the description:
image

**Review by andrewhlu — CHANGES_REQUESTED** [review]
It looks like your PR contains changes to the `javascript/package-lock.json` file. You should not be modifying this file unless you are updating the project's dependencies.

Run the following commands in the base directory of the project to remove these changes from this PR:
```sh
git checkout origin/main -- javascript/package-lock.json
git commit -m "Revert changes to package-lock.json"
git push
```

**Review by pconrad — CHANGES_REQUESTED** [review]
You should remove the changes to package-lock.json from this PR.

package-lock.json should never be changed unless you are ALSO changing package.json.

To fix this: 

checkout your branch.  Then:

```
git checkout origin/main -- javascript/package-lock.json
git commit -m "Revert changes to package-lock.json"
git push origin your-branch-name
```

**Review by pconrad — CHANGES_REQUESTED** [review]
Generally speaking, for a PR such as this one that changes the appearance of a page, we want to see a screenshot of before and after in the PR description.  Please add that.

**Review by pconrad — APPROVED** [review]

**Comment by pconrad** [comment]
This one is mergeable (I've approved it and tested it on QA)... it just needs a new peer code review (now that various changes have been made).

**Review by bowenduanmu — APPROVED** [review]
LGTM and required changes are updated.

**Pull request merged**
