### PR TITLE
7pm-3 at and jc - Fixed SearchByUser error when you are admin but not member

### PR DESCRIPTION
**Pull request by alvin-tu**
In this PR, team 7pm-3, we fixed the Search Messages by User by allowing to search messages on the Mapache app if you are a member OR an admin.

### CODE REVIEW

**Review by Sleipnir2000 — APPROVED** [review]
LGTM

**Review by TranNicholas — APPROVED** [review]
LGTM

**Review by mdeirossi — DISMISSED** [review]
LGTM

**Comment by khalidmihlar** [comment]
LGTM

**Review by khalidmihlar — APPROVED** [review]
LGTM

**Review by JacquelineMai — CHANGES_REQUESTED** [review]
The code changes themselves look good, but I think the tests need to be extended rather than simply modified. Instead of changing the old tests to use `isMemberOrAdmin`, you should add at least one test for the SearchByUser feature where the user is an admin but not a member, to cover the specific case that had been causing this bug.

You can do this by duplicating the `test_usersearch_messages` test, but changing the line
```
when(mockAuthControllerAdvice.getIsMember(anyString())).thenReturn(true);
```
to
```
when(mockAuthControllerAdvice.getIsAdmin(anyString())).thenReturn(true);
```
and adding the line
```
when(mockAuthControllerAdvice.getIsMember(anyString())).thenReturn(false);
```
The rest of the body of the test can remain the same, since we expect the same behavior.

You'll also have to give these two tests (the one for the `member` user and the one for the `admin` user) slightly different names- for documentation purposes, those test names should reflect the specific case each one covers. For example, `test_userseach_messages_member`, etc

**Review by btk5h — APPROVED** [review]
@JacquelineMai The `getIsMemberOrAdmin` function already has test coverage, so we can assume that it works correctly. It is technically possible to add test cases covering `getIsMember` and `getIsAdmin` explicitly, but there's some added complexity to that due to the entire auth utils module being mocked.

**Review by mdeirossi — APPROVED** [review]
LGTM

**Pull request merged**
